/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

/**
 *
 * @author Usuario
 */
public class Pregunta extends javax.swing.JPanel {

    /**
     * Creates new form Pregunta
     */
    public Pregunta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pregunta = new javax.swing.JLabel();
        TextoPregunta = new javax.swing.JLabel();
        RespuestaCorrecta = new javax.swing.JLabel();
        Correcta = new javax.swing.JLabel();
        RespuestaIncorrecta = new javax.swing.JLabel();
        Incorrecta1 = new javax.swing.JLabel();
        Incorrecta2 = new javax.swing.JLabel();
        Incorrecta3 = new javax.swing.JLabel();
        ImagenFondo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pregunta.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        Pregunta.setText("Pregunta");
        jPanel1.add(Pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 153, 26));

        TextoPregunta.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        jPanel1.add(TextoPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 370, 29));

        RespuestaCorrecta.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        RespuestaCorrecta.setText("Respuesta Correcta");
        jPanel1.add(RespuestaCorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 370, -1));

        Correcta.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        Correcta.setText("jLabel4");
        jPanel1.add(Correcta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 370, -1));

        RespuestaIncorrecta.setFont(new java.awt.Font("Raleway", 1, 12)); // NOI18N
        RespuestaIncorrecta.setText("Respuestas Incorrectas");
        jPanel1.add(RespuestaIncorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 123, 370, -1));

        Incorrecta1.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        Incorrecta1.setText("jLabel6");
        jPanel1.add(Incorrecta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 145, 370, -1));

        Incorrecta2.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        Incorrecta2.setText("jLabel7");
        jPanel1.add(Incorrecta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 167, 370, -1));

        Incorrecta3.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        Incorrecta3.setText("jLabel8");
        jPanel1.add(Incorrecta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 189, 370, -1));
        jPanel1.add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 380, 211));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Correcta;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JLabel Incorrecta1;
    private javax.swing.JLabel Incorrecta2;
    private javax.swing.JLabel Incorrecta3;
    private javax.swing.JLabel Pregunta;
    private javax.swing.JLabel RespuestaCorrecta;
    private javax.swing.JLabel RespuestaIncorrecta;
    private javax.swing.JLabel TextoPregunta;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
